# Generated by Django 3.1.7 on 2021-05-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('nature', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administrative_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('onset_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'allergy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('performed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blood_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_role', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HpContact',
            fields=[
                ('hp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hp_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invalidity',
            fields=[
                ('invalidity_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'invalidity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'med_alert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('implant_date', models.DateField()),
            ],
            options={
                'db_table': 'med_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('onset_date', models.DateField()),
            ],
            options={
                'db_table': 'medication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_ingredient_brand_name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'medicine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedProblem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('onset_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'med_problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('given_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pc', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('insur_number', models.CharField(max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recom_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'recommendation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(blank=True, max_length=100, null=True)),
                ('observations', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'social_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('surgery_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('procedure_date', models.DateField()),
            ],
            options={
                'db_table': 'surgery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccination_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('vaccination_date', models.DateField()),
            ],
            options={
                'db_table': 'vaccination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField(blank=True, null=True)),
                ('diastolic', models.IntegerField(blank=True, null=True)),
                ('measured_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vital_signs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationDisease',
            fields=[
                ('vaccination', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.vaccination')),
            ],
            options={
                'db_table': 'vaccination_disease',
                'managed': False,
            },
        ),
    ]
